development:
  adapter: redis
  url: redis://unimeetapp-development.ckfbsrxa15vu.us-west-1.rds.amazonaws.com:6379/1
  channel_prefix: UniMeetApp_production

test:
  adapter: async

production:
  adapter: redis
  url: redis://unimeetapp-development.ckfbsrxa15vu.us-west-1.rds.amazonaws.com:6379/1
  channel_prefix: UniMeetApp_production